name = "slackworker"
main = "src/worker.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[observability]
enabled = true

[[queues.consumers]]
queue = "slackqueue"

[[queues.producers]]
queue = "slackqueue"
binding = "SQUEUE"
