name = "slackworker"
main = "src/worker.ts"
compatibility_date = "2023-08-20"

workers_dev = false

[[queues.consumers]]
queue = "slackqueue"

# [[queues.producers]]
# queue = "slackqueue"
# binding = "SQUEUE"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
