name = "slackworker"
main = "src/worker.ts"
compatibility_date = "2023-08-20"

workers_dev = false

[[queues.consumers]]
queue = "slackqueue"

[[queues.producers]]
queue = "slackqueue"
binding = "SQUEUE"
