name = "slackworker"
main = "src/worker.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[[queues.consumers]]
queue = "slackqueue"

[[queues.producers]]
queue = "slackqueue"
binding = "SQUEUE"
