name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
        - README.md


permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            NOTIFY_CHANNEL
        env:
          NOTIFY_CHANNEL: ${{ secrets.NOTIFY_CHANNEL }}
